In [ ]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
import sys

np.set_printoptions(threshold=sys.maxsize)
from IPython.display import display

pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", 500)
pd.set_option("display.width", 1000)

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
import platform

path = "c:/Windows/Fonts/malgun.ttf"
from matplotlib import font_manager, rc

if platform.system() == "Darwin":
    rc("font", family="AppleGothic")
elif platform.system() == "Windows":
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc("font", family=font_name)
else:
    print("Unknown system... sorry~~~~")

In [3]:
import tensorflow as tf
import keras

Using TensorFlow backend.

In [4]:
from keras import models
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding
from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.callbacks import ModelCheckpoint, EarlyStopping

In [5]:
title_basic = pd.read_csv("./data/title_basic.csv")

In [6]:
title_basic

          tconst titleType                    primaryTitle                   originalTitle  isAdult  startYear endYear runtimeMinutes                  genres  averageRating  numVotes
0      tt0035423     movie                  Kate & Leopold                  Kate & Leopold        0       2001      \N            118  Comedy,Fantasy,Romance            6.4     76369
1      tt0036606     movie     Another Time, Another Place     Another Time, Another Place        0       1983      \N            118               Drama,War            6.5       243
2      tt0061876     movie                   The Commissar                        Komissar        0       1987      \N            110               Drama,War            7.5      1303
3      tt0062181     movie                    Rece do góry                    Rece do góry        0       1981      \N             76                   Drama            6.6       284
4      tt0064820     movie          The Plot Against Harry          The Plot Against Harry        0       1989      \N             81                  Comedy            6.8       276
...          ...       ...                             ...                             ...      ...        ...     ...            ...                     ...            ...       ...
69427  tt9905462     movie                       Pengalila                       Pengalila        0       2019      \N            111                   Drama            8.8       550
69428  tt9906644     movie                       Manoharam                       Manoharam        0       2019      \N            122            Comedy,Drama            6.9       301
69429  tt9911196     movie  De Beentjes van Sint-Hildegard  De Beentjes van Sint-Hildegard        0       2020      \N            103            Comedy,Drama            7.8       496
69430  tt9911774     movie       Padmavyuhathile Abhimanyu       Padmavyuhathile Abhimanyu        0       2019      \N            130                   Drama            8.0       262
69431  tt9914286     movie               Sokagin Çocuklari               Sokagin Çocuklari        0       2019      \N             98            Drama,Family            6.5       195

[69432 rows x 11 columns]

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
count_vect = CountVectorizer(min_df=0, ngram_range=(1, 2))
genre_mat = count_vect.fit_transform(title_basic["genres"])
print(genre_mat.shape)

(69432, 252)

In [9]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim.shape)
print(genre_sim[:2])

(69432, 69432)
[[1.         0.         0.         0.         0.4472136  0.25819889
  0.         0.         0.         0.         0.51639778 0.
  0.         0.2        0.         0.         0.         0.
  0.4472136  0.         0.         0.4472136  0.         0.
  0.         0.         0.         0.6        0.2        0.
  0.         0.25819889 0.25819889 0.4472136  0.         0.
  0.         0.         0.25819889 0.25819889 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.2        0.2        0.         0.51639778 0.
  0.         0.4472136  0.         0.4        0.25819889 0.4
  0.6        0.         0.2        0.2        0.         0.
  0.4472136  0.25819889 0.         0.2        0.         0.2
  0.         0.4        0.         0.2        0.         0.
  0.25819889 0.         0.         0.         0.         0.4472136
  0.         0.25819889 0.25819889 0.4472136  0.         0.4472136
  0.         0.4472136  0.         0.         0.         0.25819889
  0.4472136  0.4472136  0.         0.6        0.25819889 0.2
  0.2        0.         0.4472136  0.         0.4472136  0.25819889
  0.2        0.4472136  0.2        0.         0.2        0.2
  0.25819889 0.         0.2        0.         0.2        0.4
  0.         0.         0.25819889 0.         0.         0.
  0.4472136  0.         0.51639778 0.4472136  0.4472136  0.4
  0.         0.25819889 0.25819889 0.4        0.25819889 0.
  0.         0.4472136  0.         0.         0.         0.
  0.2        0.2        0.         0.         0.         0.
  0.         0.         0.4472136  0.         0.         0.25819889
  0.         0.4472136  0.2        0.25819889 0.         0.51639778
  0.         0.2        0.         0.25819889 0.4        0.25819889
  0.25819889 0.         0.         0.         0.         0.
  0.4472136  0.2        0.         0.         0.2        0.2
  0.51639778 0.4472136  0.2        0.         0.2        0.4472136
  0.         0.         0.25819889 0.         0.         0.25819889
  0.         0.         0.         0.         0.         0.
  0.         0.2        0.         0.         0.4        0.
  0.         0.         0.         0.         0.         0.
  0.4472136  0.2        0.         0.         0.         0.16903085
  0.         0.         0.2        0.         0.         0.4472136
  0.25819889 0.         0.25819889 0.         0.         0.4472136
  0.         0.         0.         0.         0.         0.2
  0.         0.2        0.         0.         0.         0.
  0.         0.25819889 0.         0.         0.25819889 0.25819889
  0.         0.         0.         0.         0.16903085 0.25819889
  0.         0.         0.         0.25819889 0.25819889 0.
  0.25819889 0.         0.         0.77459667 0.25819889 0.
  0.         0.4472136  0.         0.6        0.         0.
  0.         0.         0.         0.         0.         0.4472136
  0.         0.         0.2        0.16903085 0.         0.
  0.2        0.25819889 0.2        0.         0.         0.25819889
  0.         0.4472136  0.         0.         0.         0.
  0.25819889 0.25819889 0.2        0.2        0.25819889 0.
  0.         0.2        0.25819889 0.4472136  0.4472136  0.
  0.4472136  0.25819889 0.         0.4        0.         0.
  0.         0.2        0.25819889 0.         0.25819889 0.2
  0.51639778 0.4472136  0.         0.4472136  0.4472136  0.
  0.         0.6        0.4472136  0.51639778 0.2        0.
  0.         0.         0.         0.         0.         0.
  0.2        0.25819889 0.4472136  0.         0.         0.
  0.4472136  0.25819889 0.2        0.51639778 0.         0.25819889
  0.         0.         0.2        0.25819889 0.         0.
  0.4472136  0.         0.         0.2        0.         0.
  0.         0.25819889 0.25819889 0.         0.         0.
  0.         0.         0.4472136  0.         0.         0.
  0.         0.25819889 0.4472136  0.4472136  0.6        0.50709255
  0.51639778 0.         0.2        0.25819889 0.         0.
  0.2        0.25819889 0.2        0.4472136  0.4472136  0.
  0.         0.         0.         0.         0.         0.
  0.         0.4472136  0.51639778 0.25819889 0.         0.2
  0.2        0.         0.51639778 0.25819889 0.4472136  0.
  0.2        0.25819889 0.51639778 0.4472136  0.2        0.
  0.2        0.4472136  0.4472136  0.2        0.4472136  0.
  0.         0.         0.         0.4472136  0.4472136  0.
  0.         0.2        0.2        0.         0.2        0.
  0.4472136  0.         0.         0.25819889 0.         0.4472136
  0.25819889 0.         0.         0.         0.         0.
  0.         0.         0.         0.2        0.         0.
  0.         0.25819889 0.         0.         0.2        0.
  0.25819889 0.4472136  0.2        0.         0.25819889 0.4472136
  0.         0.25819889 0.         0.         0.         0.25819889
  0.6        0.         0.4472136  0.         0.2        0.4472136
  0.         0.         0.         0.25819889 0.         0.2
  0.         0.4        0.         0.4        0.4472136  0.25819889
  0.4472136  0.         0.2        0.2        0.4        0.
  0.         0.         0.         0.25819889 0.2        0.2
  0.         0.         0.25819889 0.         0.4472136  0.25819889
  0.6        0.4472136  0.         0.         0.         0.
  0.2        0.51639778 0.         0.         0.         0.
  0.         0.         0.         0.4472136  0.2        0.
  0.         0.         0.51639778 0.         0.4472136  0.2
  0.4472136  0.         0.         0.         0.         0.
  0.         0.         0.4472136  0.25819889 0.         0.
  0.25819889 0.25819889 0.         0.4472136  0.         0.
  0.25819889 0.25819889 0.4472136  0.         0.         0.25819889
  0.         0.         0.         0.         0.         0.2
  0.2        0.         0.2        0.         0.2        0.
  0.         0.4472136  0.         0.2        0.         0.4472136
  0.2        0.         0.2        0.         0.         0.
  0.25819889 0.25819889 0.         0.         0.         0.
  0.25819889 0.         0.2        0.         0.         0.25819889
  0.         0.4472136  0.25819889 0.         0.2        0.
  0.         0.         0.         0.         0.25819889 0.
  0.2        0.         0.2        0.         0.25819889 0.
  0.25819889 0.         0.4472136  0.         0.2        0.
  0.         0.         0.4        0.25819889 0.4472136  0.
  0.25819889 0.25819889 0.         0.         0.         0.
  0.         0.25819889 0.25819889 0.2        0.25819889 0.
  0.4472136  0.2        0.         0.         0.2        0.25819889
  0.4        0.2        0.         0.         0.         0.
  0.25819889 0.4        0.2        0.4472136  0.         0.
  0.         0.         0.2        0.25819889 0.         0.
  0.         0.         0.25819889 0.         0.         0.
  0.4472136  0.6        0.25819889 0.25819889 0.4472136  0.
  0.2        0.         0.2        0.         0.         0.2
  0.         0.2        0.2        0.         0.2        0.4472136
  0.2        0.25819889 0.         0.2        0.2        0.
  0.2        0.         0.         0.25819889 0.         0.25819889
  0.         0.         0.         0.         0.         0.2
  0.         0.         0.         0.         0.2        0.
  0.         0.         0.25819889 0.         0.2        0.25819889
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.25819889
  0.2        0.         0.25819889 0.         0.2        0.4472136
  0.25819889 0.4472136  0.25819889 0.4472136  0.         0.
  0.4472136  0.         0.2        0.         0.         0.4472136
  0.         0.         0.2        0.         0.2        0.
  0.25819889 0.         0.         0.2        0.         0.4472136
  0.25819889 0.2        0.2        0.         0.         0.
  0.         0.16903085 0.         0.         0.25819889 0.
  0.         0.2        0.25819889 0.2        0.25819889 0.4472136
  0.         0.         0.         0.         0.         0.2
  0.25819889 0.51639778 0.         0.25819889 0.2        0.16903085
  0.4472136  0.         0.2        0.2        0.         0.
  0.         0.         0.         0.         1.         0.
  0.         0.2        0.25819889 0.4        0.4        0.
  0.4472136  0.         0.2        0.6        0.51639778 0.4
  0.2        0.25819889 0.4472136  0.25819889 0.2        0.25819889
  0.         0.         0.         0.2        0.         0.25819889
  0.         0.25819889 0.         0.         0.         0.
  0.         0.4472136  0.2        0.         0.         0.
  0.         0.         0.4472136  0.         0.         0.
  0.2        0.         0.         0.2        0.         0.
  0.         0.         0.25819889 0.4472136  0.2        0.25819889
  0.         0.         0.         0.25819889 0.         0.4472136
  0.2        0.2        0.         0.         0.25819889 0.
  0.25819889 0.2        0.         0.         0.         0.2
  0.         0.2        0.2        0.         0.4472136  0.16903085
  0.25819889 0.         0.         0.25819889 0.         0.25819889
  0.         0.         0.4472136  0.2        0.2        0.4472136
  0.         0.25819889 0.         0.         0.         0.4472136
  0.4472136  0.         0.2        0.4472136  0.2        0.
  0.         0.         0.         0.4472136  0.         0.6
  0.25819889 0.         0.         0.2        0.         0.
  0.2        0.         0.         0.4        0.         0.4472136
  0.2        0.         0.         0.25819889 0.         0.2
  0.         0.4        0.2        0.25819889 0.25819889 0.
  0.4472136  0.4472136  0.2        0.         0.25819889 0.
  0.         0.         0.51639778 0.         0.4472136  0.
  0.2        0.         0.         0.2        0.         0.
  0.         0.25819889 0.         0.         0.         0.
  0.25819889 0.4472136  0.4472136  0.25819889 0.2        0.2
  0.         0.2        0.         0.         0.         0.2
  0.         0.         0.4        0.         0.25819889 0.
  0.2        0.2        0.         0.25819889 0.         0.4
  0.         0.4472136  0.4472136  0.25819889 0.4472136  0.
  0.         0.25819889 0.         0.25819889 0.         0.
  0.4        0.         0.         0.4472136  0.2        0.2
  0.         0.         0.25819889 0.2        0.         0.
  0.         0.25819889 0.25819889 0.         0.4472136  0.2
  0.4472136  0.4472136  0.         0.25819889 0.         0.
  0.         0.         0.2        0.         0.         0.
  0.         0.25819889 0.25819889 0.         0.16903085 0.4472136
  0.         0.         0.         0.         0.         0.
  0.         0.         0.2        0.         0.2        0.25819889
  0.2        0.         0.4472136  0.         0.25819889 0.25819889
  0.         0.2        0.4472136  0.25819889 0.50709255 0.
  0.         0.25819889 0.25819889 0.25819889 0.         0.
  0.         0.         0.         0.25819889 0.4472136  0.
  0.4        0.4472136  0.         0.4472136  0.4472136  0.2
  0.         0.25819889 0.         0.         0.16903085 0.
  0.         0.         0.         0.25819889 0.         0.
  0.25819889 0.2        0.4472136  0.         0.         0.
  0.4        0.         0.25819889 0.         0.25819889 0.4472136
  0.         0.         0.2        0.4        0.25819889 0.25819889
  0.         0.2        0.25819889 0.25819889 0.         0.25819889
  0.         0.         0.25819889 0.         0.51639778 0.
  0.25819889 0.         0.25819889 0.         0.16903085 0.
  0.         0.4472136  0.25819889 0.2        0.25819889 0.2
  0.         0.51639778 0.         0.         0.2        0.
  0.         0.2        0.         0.2        0.25819889 0.
  0.2        0.2        0.         0.         0.25819889 0.
  0.         0.         0.4472136  0.         0.4        0.25819889
  0.2        0.2        0.         0.         0.         0.
  0.4472136  0.2        0.         0.2        0.         0.4472136
  0.2        0.         0.25819889 0.         0.2        0.2
  0.         0.         0.         0.         0.2        0.
  0.25819889 0.         0.4        0.         0.2        0.
  0.         0.25819889 0.4472136  0.         0.4472136  0.
  0.25819889 0.         0.2        0.4472136  0.         0.
  0.2        0.25819889 0.         0.2        0.25819889 0.4472136
  0.         0.25819889 0.         0.6        0.         0.
  0.         0.         0.         0.4472136  0.         0.
  0.         0.4472136  0.4472136  0.51639778 0.         0.
  0.2        0.         0.4472136  0.4472136  0.2        0.25819889
  0.         0.4472136  0.         0.4        0.4        0.25819889
  0.         0.         0.4472136  0.         0.4        0.
  0.2        0.25819889 0.4472136  0.         0.         0.
  0.         0.         0.2        0.         0.         0.2
  0.         0.         0.         0.         0.         0.2
  0.         0.         0.         0.         0.25819889 0.25819889
  0.2        0.         0.         0.2        0.         0.
  0.         0.         0.25819889 0.25819889 0.4472136  0.
  0.         0.25819889 0.         0.2        0.25819889 0.
  0.25819889 0.         0.         0.4472136  0.2        0.
  0.4472136  0.         0.4472136  0.25819889 0.2        0.25819889
  0.2        0.51639778 0.         0.2        0.2        0.
  0.25819889 0.         0.2        0.         0.25819889 0.
  0.         0.         0.25819889 0.         0.         0.
  0.         0.25819889 0.         0.         0.         0.
  0.25819889 0.25819889 0.         1.         0.         0.4472136
  0.         0.         0.2        0.4        0.2        0.
  0.3380617  0.         0.25819889 0.4472136  0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.25819889 0.         0.         0.2        0.2
  0.         0.         0.         0.25819889 0.         0.
  0.25819889 0.         0.4472136  0.4472136  0.25819889 0.
  0.         0.2        0.25819889 0.25819889 0.         0.
  0.25819889 0.         0.         0.2        0.         0.25819889
  0.16903085 0.4472136  0.         0.         0.         0.
  0.         0.         0.         0.         0.25819889 0.2
  0.25819889 0.2        0.4472136  0.4        0.4472136  0.
  0.         0.         0.4472136  0.         0.4        0.
  0.         0.         0.4472136  0.         0.25819889 0.
  0.2        0.51639778 0.         0.         0.         0.
  0.         0.         0.         0.4472136  0.4472136  0.4
  0.         0.         0.         0.6        0.2        0.
  0.4472136  0.         0.         0.2        0.2        0.4472136
  0.         0.         0.         0.         0.2        0.
  0.         0.         0.         0.4472136  0.2        0.
  0.2        0.4472136  0.25819889 0.2        0.         0.
  0.         0.         0.4472136  0.         0.         0.25819889
  0.4472136  0.         0.4472136  0.         0.4472136  0.
  0.2        0.25819889 0.         0.         0.         0.
  0.25819889 0.         0.         0.2        0.4472136  0.
  0.4472136  0.         0.4472136  0.         0.25819889 0.4472136
  0.77459667 0.2        0.25819889 0.         0.2        0.
  0.         0.         0.         0.51639778 0.         0.
  0.2        0.2        0.25819889 0.         0.25819889 0.
  0.         0.16903085 0.         0.         0.4        0.
  0.         0.4472136  0.2        0.4472136  0.2        0.2
  0.25819889 0.         0.         0.         0.25819889 0.
  0.25819889 0.         0.25819889 0.         0.         0.
  0.4472136  0.         0.         0.2        0.25819889 0.
  0.2        0.         0.2        0.         0.4472136  0.25819889
  0.2        0.2        0.         0.4472136  0.4472136  0.
  0.         0.51639778 0.         0.         0.         1.
  0.         0.25819889 0.         0.         0.         0.
  0.6        0.4472136  0.51639778 0.         0.         0.
  0.2        0.         0.2        0.         0.2        0.
  0.4        0.2        0.25819889 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.25819889 0.25819889 0.2        0.         0.6        0.
  0.6        0.2        0.2        0.2        0.         0.
  0.         0.         0.4472136  0.         0.25819889 0.25819889
  0.25819889 0.         0.         0.25819889 0.         0.4472136
  0.         0.         0.4472136  0.         0.4        0.
  0.25819889 0.25819889 0.25819889 1.         0.25819889 0.25819889
  0.         0.         0.51639778 0.         0.4        0.4
  0.25819889 0.         0.         0.         0.         0.
  0.         0.         0.         0.25819889 0.         0.4
  0.4472136  0.         0.         0.2        0.25819889 0.
  0.         0.         0.2        0.4472136  0.4472136  0.25819889
  0.2        0.25819889 0.2        0.         0.         0.
  0.2        0.51639778 0.2        0.         0.         0.
  0.16903085 0.25819889 0.         0.         0.4        0.25819889
  0.4472136  0.25819889 0.         0.25819889 0.2        0.2
  0.         0.4472136  0.2        0.4        0.2        0.25819889
  0.         0.         0.2        0.4472136  0.2        0.25819889
  0.25819889 0.2        0.         0.4472136  0.4472136  0.
  0.         0.         0.4        0.         0.2        0.
  0.25819889 0.         0.4472136  0.2        0.2        0.
  0.4472136  0.         0.         0.         0.2        0.2
  0.4472136  0.4472136  0.         0.2        0.25819889 0.
  0.         0.2        0.25819889 0.         0.25819889 0.
  0.4472136  0.4472136  0.4472136  0.         0.         0.4472136
  0.         0.         0.2        0.4472136  0.2        0.4472136
  0.         0.         0.         0.         0.25819889 0.4
  0.         0.         0.2        0.         0.         0.
  0.4472136  0.         0.         0.4        0.         0.
  0.2        0.         0.         0.25819889 0.25819889 0.16903085
  0.         0.         0.2        0.         0.         0.25819889
  0.4        0.         0.         0.         0.6        0.4472136
  0.         0.         0.         0.25819889 0.         0.4472136
  0.         0.6        0.         0.4472136  0.2        0.
  0.2        0.25819889 0.25819889 0.         0.4472136  0.
  0.         0.25819889 0.         0.         0.         0.25819889
  0.4472136  0.25819889 0.4        0.25819889 0.25819889 0.
  0.         0.         0.25819889 0.2        0.         0.4472136
  0.         0.25819889 0.         0.         0.         0.
  0.25819889 0.         0.25819889 0.4        0.         0.4472136
  0.25819889 0.51639778 0.4472136  0.4472136  0.         0.4
  0.25819889 0.2        0.         0.4        0.         0.
  0.2        0.25819889 0.4472136  0.         0.         0.
  0.2        0.         0.4472136  0.2        0.4        0.
  0.25819889 0.         0.4472136  0.         0.         0.4472136
  0.         0.16903085 0.         0.25819889 0.         0.
  0.51639778 0.         0.         0.25819889 0.4472136  0.51639778
  0.25819889 0.2        0.4472136  0.         0.         0.51639778
  0.25819889 0.4472136  0.         0.25819889 0.25819889 0.25819889
  0.25819889 0.         0.         0.         0.         0.4472136
  0.4472136  0.         0.         0.2        0.         0.4472136
  0.51639778 0.25819889 0.         0.         0.         0.
  0.2        0.         0.4472136  0.         0.2        0.
  0.4        0.25819889 0.2        0.         0.         0.
  0.         0.         0.25819889 0.25819889 0.16903085 0.25819889
  0.4472136  0.         0.         0.16903085 0.         0.
  0.2        0.         0.2        0.77459667 0.2        0.4
  0.         0.25819889 0.4472136  0.4472136  0.4472136  0.77459667
  0.         0.         0.2        0.         0.         0.4472136
  0.2        0.         0.         0.25819889 0.4472136  0.
  0.2        0.         0.         0.77459667 0.         0.
  0.         0.         0.25819889 0.         0.2        0.

In [10]:
genre_sim_sorted_index = genre_sim.argsort()[:, ::-1]
genre_sim_sorted_index[:1]

array([[    0,   790,  9648, 53486, 53255, 10126, 67914, 49044, 49032,
        49001, 25000, 12831, 48419, 13434, 47359, 13707, 13952, 14052,
        46737,  9581,  8853,  8267, 57974,  6443,  6452, 58873,  1305,
        58660, 58484,  7038,  7141, 28152,  7226, 57541, 67427,  7572,
        57120,  7726, 56705, 14255, 45628, 27609, 24796, 37450, 19811,
        36795, 36458, 36146, 20781, 29952, 21382, 34200, 22222, 33097,
        22887, 22974, 31798, 31796, 31393, 24069, 37538, 37609, 19631,
        16689, 45592, 45421, 45017, 15505, 15537, 43893, 43118, 16810,
        38933, 29301, 16929, 42050, 41785, 41649, 40436, 18188,  6435,
        10054,  3705, 66923, 62828,  5317,  2006,  4486,  1587,  1523,
         2299, 61950,  5622,  2473,  2495, 67144, 65075,  3696, 61657,
         4827, 63582,  3439,  3687,  4018,  5805,  6173, 66558, 26266,
        66620, 59702, 60001, 63153, 40978, 40759,  3690, 17809, 16175,
        40538, 64849, 18350, 44855, 18455, 44902, 39351, 18638, 64814,
         3068, 17562, 16828, 43614, 15905, 16346, 16401, 43828,  3602,
         3597, 42275, 43127, 39156, 68371,  3668,  3384, 42091, 17048,
         3271, 18661,  6239, 18867,  2176, 34365, 34219, 21844, 22088,
         1911, 68961, 33122,  1895,  1887,   261, 22969, 66595, 31469,
        66618, 31375, 31045, 23634, 30828, 23770, 66196, 68859, 65065,
        21218, 38908, 19077, 38288, 19311, 38058,  2595,  2538, 19795,
        37355, 37146, 19977, 36625, 20292, 20354,  2398, 36050, 35836,
        68840, 35099, 19497, 45748, 14864,  8068, 67178,  7579, 57203,
         5066,  5011, 56835, 56824,  4989,  7942,  8157,  7466, 56273,
         8188,  8198,  4956,  8209, 61547, 56031,  8340, 55799,  7570,
        67428,  3925, 58498,  6292,  6386,  6081,  6005,  6538, 59895,
         6656,  6722, 58611,  5636, 61022, 58466, 58262, 67369, 58158,
        60589, 60641,  7189, 67400,  5383, 55195, 55126,  8873, 13898,
        62257, 13315, 68013, 47660,  4395,  4299, 13751, 47204, 47036,
         4290, 54857,  4069, 68092, 46459, 46456, 62995, 14362, 14449,
        14679,  4037, 62256, 48944, 62138,  4662, 67142, 53954,  4837,
        30642,  4782, 52890, 52836, 52637, 10826, 10884, 11277, 11290,
        50837, 50702, 50382, 11885, 11931,  4738,  1458, 30702, 66833,
        30252, 26860, 26233, 69327, 26512, 29716, 29148, 25216, 27451,
        27103, 24735, 29637, 30068, 26164, 27693, 69291, 29796, 24778,
        25042, 25367, 39817,  6630, 27739, 58696,  6710, 39698,  6723,
         7847, 27829, 18305, 17025, 39883, 58552, 39939,  7788, 39970,
        58871, 18567,  6577, 39374, 59257,  6348, 29592, 59130, 18848,
        39038,  6442, 18801,  7927, 16971, 18687, 39320,  7903,  6571,
        29550,  6791, 67436, 41276, 57871, 57739, 57732,  7318, 57595,
        57183, 57587,  7371, 41339,  7375, 67415, 57522,  7416, 41081,
        27933,  7510, 27918, 41628,  6832, 17862, 18123, 56908,  6875,
        40250, 40273,  6897, 17944, 18948, 17163,  6987, 41765, 27881,
        56917, 58067, 40549,    60, 38621, 38726, 24375, 61038,  5332,
        36883,  1401, 20063,  5394,  5408,  5409, 37194, 37551, 19928,
         5438, 19856, 60635, 19823, 37407,  5588, 37436,  5192, 36564,
         5188, 61096, 61585, 61565,  4910, 27211, 20700,  4957,  4958,
        36057,  5023, 68766, 61339, 61295, 36398, 61176, 36504, 27328,
        36521,  5597, 37584, 59343, 25641, 38308, 27517, 19221, 38354,
        19211, 38369,  6059,   504, 27521, 19694,  6141, 19085, 19079,
        27566,  6192, 24611, 38648, 38691,  5983,  5942,  5911,  5891,
         5633, 37619,   468, 37621,  5639,  5643, 60354,  5654, 19569,
        19567, 37850, 38000, 38005,  5779, 60003,  5890, 24438,   661,
        42376, 56618, 47176, 10566, 10633, 47034, 52211, 10719, 13854,
        10740, 47172, 51985,  8060, 28458, 47260, 51953, 51914, 10875,
        25096, 13624, 47559, 28844, 46534, 46511, 28439, 14537,   801,
        28894, 10083, 10117, 14396, 53020, 14339, 14322, 10204, 10243,
        10262, 46333, 52786, 52765, 10352, 28876, 47576, 47646, 13482,
        12700, 11475, 50824, 12582, 12486, 12406, 11670, 12398, 49388,
        11708, 12290, 67858, 11776, 49673, 49680, 28573, 12075, 11936,
           99, 50963, 13475, 50986, 11053, 26323, 47954, 48036, 13233,
        48149, 13145, 48229, 24014, 28645, 51283, 12873,   899, 48745,
        51097, 51074, 11346, 45933, 28401, 14627, 28220, 16297,  8442,
        16272, 16192, 16177,  8557,  8571, 16091,  8656,  8659, 43613,
        55341, 15958,  8754, 55273, 68263,  8859,  8364,  1191, 15768,
        56054,  8118, 42320, 29231, 35749, 42415, 56334, 42457, 56266,
        42555,  8197, 28147,  8220, 42726,  8228, 56141, 16463, 42965,
        15785, 28296, 28944, 44920, 28331,  9612, 15114,  9636, 53868,
        53779, 67651,  9738,  9769, 45377, 14876, 45431,  9823, 14822,
         9878, 53462, 24807,  9578, 44895, 55090, 54078, 67581, 25183,
        44152, 44278, 44280, 29070,  9313,  9338, 54303,  9374, 54269,
         9415, 44720, 54200, 54197, 44746,  9504, 35764, 11965,  4350,
        30920, 65273,  1560, 65313, 23708, 23698,  4303, 34791, 69385,
         3423, 62302, 34702, 33419, 62594, 22983,  2518, 66205,  3453,
         3535,  1558, 63987, 21043, 62127,  2618, 62043,   376,  4610,
        26490, 64053, 64051, 69017, 62146, 22890, 21201,  4550, 30826,
        33287, 27023, 30067,  4483, 21303, 34534,  2448, 30249,  3747,
         2772, 33808, 21939, 23289,  2279,  3780,   325, 34165, 31553,
         3580,  3745, 21893,  3733,  3732,  3721,  2340, 21789, 23370,
         2364, 63265, 34255, 63175,    27,  3584, 34504, 30032,  3592,
        23565, 31129, 21582, 22033, 26599,  3989, 33678, 23179, 31272,
        63142, 63604, 23434, 26121, 23354, 32908, 27062, 33047, 30684,
         2939,  1747, 35628, 66793, 65128, 35400,  2934,  1530, 67119,
        65021, 32419,  3250,  3248, 61704, 25854,  4730,  3238, 61908,
         4717, 66803, 35381, 21013, 26647, 35694,   267, 26145, 22452,
        32920, 65070, 23957, 65061, 32445,  1738, 53336, 53283, 65615,
         9962,  2383, 53443, 53456, 53421, 54720,  2407, 26185, 28382,
         2405, 53268, 53612,  9801,  9797, 65576, 65553, 53668,  2423,
        55301,  2432,  8757, 65517, 53282, 10068, 10034, 10138,  8675,
        10163, 55472, 10167, 53050, 55488, 64981, 65673, 64957, 64949,
        52997, 55540, 55592, 65685, 55602, 65687, 65725, 10144, 28421,
        65618,  8681, 55315, 25154, 53236, 55319, 65623, 55251,  8740,
         2351, 65664, 10079,  8736, 53192,  2348, 65672, 10114, 64997,
         8711,  8775, 65495, 55243,  2589, 54371, 54360, 54957,  8942,
        65263, 54313,  8936,  8932,  9375, 54383,  9385, 55010, 54249,
        55024,  9420, 54203,  8907, 52907,  9326,  8976, 54190, 54600,
        54791, 54680,  9152,  2630, 54825, 54628, 54619, 54829,  9186,
        65192,  9190,  9240, 65247,  9246, 54414,  9306, 65200, 26628,
         2540, 28320,  9728, 53871, 65432, 53907,  9633, 26600, 55202,
        65469, 53886,  2458,  8815, 25161, 54711,  9686,  9694,  8801,
         9710, 55234, 55235,  2442,  9598, 55199, 54188,  2655, 54187,
        54145,  2635, 54115,  9491, 65187, 65160, 26161, 28278, 65385,
         2532, 54058,  9540,  9561, 55152, 65369,  9567,  9569, 61645,
        52588, 25131, 50753, 11340, 51084, 66423, 66477, 11361, 11382,
        51009, 11395, 66478,  1854, 50958, 66513, 11432, 11446, 11458,
        50889,  1835, 11487, 50848, 28533, 50829, 11501,  1829, 66421,
        51103, 26448, 11219,  1984, 66290, 51425, 66327, 51423, 51410,
        51405, 51338, 51332, 11208, 66334, 11301, 51266, 51265, 11251,
        51225, 66400, 51207, 51194, 51190, 28500, 28527, 50779,  1824,
        11129, 50750, 50406, 11753, 26348, 11773, 50350, 50329, 66712,
        11830, 11836, 11846, 11851, 50242, 11875, 11894, 50176, 11904,
        50156, 50151, 50149, 11922, 50130, 25037,  1627, 11729, 26379,
        11724, 11653, 50738, 11558, 50713, 50704, 25047, 66537, 50679,
        11581, 50615, 11629, 50542, 11719, 66538, 26445,  1789, 26431,
        11697, 11698, 50478, 50475, 66601, 11710, 51455, 51477, 52868,
        65963, 52481, 52478, 52475, 10547, 52446, 52430, 52424, 26551,
        52417, 52410, 52402, 52398, 10580, 10586, 65912, 52293, 52261,
        10672, 52220, 65938, 52163, 65948, 26199, 52498, 10516, 10506,
        52728, 10299, 10309, 28424, 10320, 10334, 10336, 26559, 52785,
        65754, 65760, 52648, 52561, 10429, 10431, 65834, 65868, 65892,
        52635, 10433, 52595, 10469, 10470, 52145, 10755,  1996, 10763,
        51673, 26533, 11007,  2021, 51658, 11039, 11046, 11052, 51581,
        66219, 51579, 51578, 11054, 11057, 51569, 51546, 11088, 51520,
        66243, 51508, 11109, 51485, 11117, 66142, 51689, 66137, 66092,
         2142, 10769, 10803, 10819,  2140, 66079, 66087, 51947, 10837,
        10854,  2083, 51723, 51867, 66117, 51860, 10896, 10920, 51791,
        51769, 10949, 51754, 51742,  8581, 64365, 64899, 25959, 59835,
         6009, 62635, 62643,  4149, 59771, 59765, 59757, 59751,  4140,
         4123, 26967,  4115, 59660, 59624, 59603, 62898, 59557, 26962,
        62962,  4052,  6186,  4289, 59856, 25602, 60144,  5659, 60332,
        60330,  5714, 60246,  4419, 25941, 60210, 60203, 60156, 60119,
        25664, 27456, 60100, 60046, 60045,  5859,  5867,  4330, 27465,
         4297, 62588, 62983, 59373, 27020, 58969, 63143, 27686, 59092,
        63150,  6453,  6481,  6483, 25983, 59023,  6523, 27707, 27658,
        58936,  6560, 26887, 58916, 63192,  3909, 27724,  3853, 58851,
         3840, 63116, 63086, 59366, 59284, 26947, 59364, 59362, 59348,
        26946, 59336, 27616, 59300, 59285,  4015,  4012, 63078, 59255,
        59243, 59222,  6359, 59210, 59204, 25581, 59180,  6398, 59133,
         4482, 27037,  6636, 61169, 61311, 25764, 61306, 61801, 61280,
        61253,  5108, 61827, 61216,  4744, 61160, 61338, 61158, 61841,
        61129, 61852, 61856,  4718, 61064,  5225,  4715, 27330, 61312,
        27107, 60962, 61508, 61615, 27161, 61569,  4852, 27205, 27155,
         4835, 25804, 61545, 61510, 27261, 61368, 61697, 61698, 61474,
         4971, 61464,  4988, 27271, 27272, 61412,  5016, 61016, 60935,
        62247, 60463,  5478,  5479, 62018, 25698, 62049, 60576, 62062,
        60508, 60479,  5577,  4601,  5465, 60427, 62099, 27427, 62110,
        25902, 60391,  5627, 62141, 62212, 60378, 27348, 60669,  5312,
        60819, 25749,  4711, 60858,  5343, 60844,  5349,  5351, 60830,
        60829, 60826,  5371, 60687, 27076,  4699, 27339,  5391, 60752,
        61977, 60713,  5427, 25901, 62010,  6635,  6648, 26650,  3315,
         7833, 56788, 56781, 56746, 64068, 28051,  7905, 64078,  7909,
         7919,  7930, 25355, 56659,  7931,  7934, 64161, 25335,  7947,
         3268,  7983, 56571, 56479, 28026,  7809, 28057, 57055,  7610,
        57151, 57143, 57130, 25371,  7663,  7664, 57062, 63971, 57056,
        57053, 26707, 57035, 57001, 56977, 56933, 56931, 64003, 26710,
         3369,  7771, 56891, 64206, 56437, 27988, 55937, 26665, 28203,
        56104, 56082, 28206, 56030, 56013,  8338,  2896, 55968, 55909,
         8242, 64782, 55898, 64792, 26664,  8445, 28250, 55792,  8486,
         8540, 64815, 56147,  3095,  8090, 25306, 56365, 56350,  8126,
        56344, 64275,  8143, 56317,  3204,  8152, 28068, 56268, 56187,
        64323, 28131,  3183,  3182, 61617, 56221, 56216, 25253, 64369,
        64385, 27998, 25393,  3793, 25461, 58377, 26842, 58349, 26820,
        26809, 58317,  6915, 58291, 58277, 27835, 58255, 63524, 58252,
         6954, 58229, 58198,  6997, 58168,  7006, 25449,  7034, 26777,
        58389, 58405, 58092,  6737, 58757,  6665, 58743, 58742, 27749,
        58727,  3777, 27762, 25487, 58643, 25480, 63520, 58590, 58559,
         6773, 58543, 58534, 63508, 58514, 27823, 26021, 11969, 58108,
        63612, 27951, 27934, 25408,  7400, 57533, 63788, 57516, 57509,
        57498,  3522, 57487,  7450,  7461, 63711, 27947, 57412, 26715,
         7518, 63943, 57322, 57310,  3427, 57287,  7552, 57570, 57626,
         7122, 57873,  7125, 63633, 25443, 57956,  3604,  7148, 57929,
        57905, 57902,  7177, 26075, 57645, 57869, 27914,  7193,  7195,
         7197, 27924, 57769, 63688, 57715, 26086, 30351, 48284, 50014,
        36880, 20131, 20137, 36830, 20164, 36800, 20174, 20176, 20193,
        36721, 36715, 36701, 36675, 29808, 20277, 36616, 36610, 29827,
        20301, 20314, 36523, 20332, 20340, 24319, 24317, 36442, 36436,
        36403, 20424, 36358, 36865, 20077, 18040, 20071, 37616, 29679,
        37591, 29689, 19770, 24395, 29698, 19797, 37394, 19806, 29707,
        19827, 37343, 37326, 37294, 19872, 37280, 37279, 37276, 19896,
        19899, 37179, 19956, 29753, 37109, 19986, 37097, 36982, 36979,
        36353, 36326, 36289, 36279, 35710, 35704, 20810, 35663, 35658,
        20835, 20857, 35595, 20880, 35577, 20903, 35548, 20907, 20919,
        20924, 20945, 35456, 20969, 35437, 35418, 35405, 35397, 35395,
        35383, 35361, 21033, 35289, 21066, 21068, 35711, 35730, 24301,
        24312, 20484, 36243, 20499, 20502, 20539, 36172, 36171, 29839,
        36106, 36104, 20581, 36081, 36074, 20610, 20742, 20614, 36032,
        35945, 20682, 35916, 35888, 20703, 35854, 35847, 29853, 35835,
        35815, 35808, 19651, 29641, 19623, 29597, 39506, 39474, 39472,
        18558, 39460, 39406, 18595, 39348, 39327, 29551, 18645, 39297,
        18659, 29554, 18662, 39222, 18717, 18733, 24462, 18766, 39106,
        39052, 18847, 18855, 18860, 38966, 24456, 38922, 18898, 39518,
        18507, 39542, 39897, 40205, 40186, 40175, 18134, 18150, 18171,
        29495, 40025, 40023, 18219, 18232, 18240, 18262, 39878, 18492,
        39873, 18300, 39843, 18317, 18344, 24504, 18353, 18429, 29545,
        18466, 39601, 39593, 18481, 38917, 18910, 37717, 38893, 38315,
        24441, 38258, 38250, 19290, 19300, 19306, 19321, 38182, 38161,
        38122, 19369, 38110, 19377, 19382, 19402, 38060, 24428, 38048,
        19418, 38034, 38009, 19484, 19504, 37890, 37883, 19525, 19574,
        37740, 19240, 19235, 19208, 19052, 38868, 18939, 38847, 18943,
        38818, 38798, 38778, 38737, 38716, 19029, 38660, 38655, 38633,
        38596, 38434, 38595, 19073, 29608, 38552, 38550, 38539, 19133,
        19134, 19135, 19136, 38480, 38479, 38438, 35276, 35266, 35229,
        23312, 32130, 22998, 32042, 23033, 23060, 31941, 31936, 31925,
        31914, 31903, 23099, 31826, 24154, 24115, 23165, 31786, 31781,
        31718, 31710, 23214, 31678, 31676, 31665, 31662, 23249, 23270,
        23276, 31602, 23282, 30107, 30082, 22936, 22727, 32706, 22603,
        32665, 22616, 22618, 32638, 22630, 32592, 22662, 22686, 22693,
        22699, 32503, 22763, 22935, 22765, 32426, 22796, 22830, 22841,
        22848, 22860, 22868, 22881, 32255, 32251, 32224, 32203, 23303,
        31480, 32722, 23346, 30271, 30807, 30794, 30790, 24048, 30782,
        23785, 30749, 30738, 30733, 30707, 24026, 23843, 30656, 23849,
        30647, 30349, 30594, 30584, 23897, 23902, 23927, 23962, 30446,
        30412, 30408, 23997, 30392, 24004, 23744, 23742, 30864, 31151,
        30192, 23378, 30227, 30236, 23400, 23404, 23423, 23433, 31320,
        23470, 31223, 23510, 31178, 31134, 30893, 23589, 23597, 23598,
        23614, 31042, 31032, 31022, 23640, 30997, 23647, 23649, 30987,
        30961, 22584, 32746, 35170, 34160, 34576, 34570, 21494, 21495,
        21508, 21511, 34528, 21522, 34511, 21540, 21543, 34401, 34391,
        21602, 21603, 24235, 21622, 34332, 21638, 21641, 34315, 21659,
        24221, 21697, 21704, 30010, 34188, 34180, 34178, 21488, 21435,
        34666, 34892, 35161, 21145, 24292, 35114, 29883, 35061, 35045,
        35038, 29905, 35007, 21243, 21245, 34991, 34873, 21418, 34833,
        21338, 34804, 21356, 29950, 21364, 34773, 34771, 34768, 24244,
        21413, 21415, 34688, 21728, 21754, 32763, 21761, 33300, 33288,
        33272, 33270, 33257, 22266, 33240, 30050, 33183, 22324, 22333,
        30056, 30063, 22368, 22371, 33064, 33058, 22393, 22398, 33018,
        22420, 22421, 33003, 32999, 32975, 32943, 32898, 32894, 22489,
        33317, 24194, 33343, 22011, 34110, 33995, 24199, 21858, 33946,
        21868, 33931, 21885, 33880, 33755, 33750, 21997, 33725, 33681,
        33363, 33673, 33651, 33580, 22081, 33559, 33557, 22100, 33492,
        22134, 33471, 22157, 33438, 22165, 40221, 40285, 50009, 46729,
        46676, 46643, 46630, 46616, 46577, 46565, 28862, 46559, 14154,
        46556, 46495, 14208, 24841, 14215, 14220, 46446, 14226, 46438,
        46433, 14233, 14234, 14237, 24839, 14262, 46321, 46315, 14307,
        46303, 14314, 46680, 46739, 40290, 24880, 13695, 24918, 47254,
        47246, 24911, 13761, 24901, 47152, 47110, 13818, 47105, 47046,
        13863, 28796, 47016, 13883, 46994, 46987, 46986, 24884, 13907,
        13933, 28827, 46854, 13987, 46799, 46754, 46752, 46749, 46291,
        46289, 24838, 46215, 45376, 14931, 14950, 45269, 14986, 45218,
        45166, 45139, 15091, 45085, 45082, 15096, 45068, 29007, 15143,
        15145, 15149, 15181, 44952, 15182, 44939, 29011, 15227, 44877,
        15236, 44858, 29023, 44829, 44805, 29006, 45479, 14832, 45855,
        46189, 46181, 14421, 46121, 14434, 14435, 46099, 46093, 14448,
        46062, 66835, 14551, 45892, 14601, 45511, 45798, 45778, 45767,
        45759, 24814, 45729, 28945, 45701, 45674, 14743, 14758, 24781,
        45519, 13688, 28764, 13647, 12708, 12385, 12403, 12412, 12421,
        49335, 49290, 49278, 12483, 49249, 49213, 12534, 49169, 12544,
        12578, 49051, 49050, 25023, 28602, 49019, 25015, 48964, 12656,
        48949, 12673, 48921, 48896, 48893, 48884, 48883, 12382, 12381,
        12374, 49735, 12021, 12033, 49959, 49944, 12047, 49932, 12068,
        12088, 12091, 49822, 49787, 12159, 12183, 49727, 49435, 12205,
        49664, 49644, 12242, 12244, 49616, 12278, 49568, 28587, 12287,
        12309, 49480, 49444, 12705, 12713, 47408, 48871, 13249, 13292,
        13308, 47932, 24986, 28677, 47843, 13366, 47835, 47829, 47813,
        13430, 28698, 47693, 13469, 24943, 47633, 47573, 47551, 13549,
        13553, 47529, 13561, 47510, 13569, 47505, 13584, 13628, 13640,
        13228, 48081, 48123, 48610, 48844, 48839, 48818, 12749, 12763,
        48781, 12775, 48725, 24991, 12840, 48645, 12868, 12869, 12887,
        48151, 12928, 48523, 48488, 48486, 13011, 48361, 48331, 13069,
        48302, 48294, 48258, 13153, 48187, 15282, 44769, 44767, 17515,
        41736, 17221, 41671, 41670, 41665, 29368, 17247, 41633, 41602,
        41593, 41578, 17275, 17287, 41514, 17318, 17324, 41481, 17338,
        17361, 41388, 17375, 17418, 17419, 17423, 41285, 17434, 17454,
        41222, 41218, 17177, 41760, 24588, 29339, 16859, 16860, 16872,
        16876, 16877, 42207, 16895, 16899, 42172, 16918, 42161, 42155,
        29338, 42090, 41810, 42078, 16972, 42066, 16985, 29349, 42010,
        42009, 41982, 17038, 24591, 41941, 41904, 41822, 17491, 41137,
        29240, 41086, 17818, 40654, 40643, 40627, 17840, 40620, 40619,
        40618, 40581, 40561, 40542, 24564, 17896, 40503, 40492, 17922,
        40474, 40473, 17935, 17939, 17942, 29409, 17947, 17967, 17968,
        40335, 40322, 18021, 18024, 24566, 17772, 40749, 40942, 17553,
        41083, 41079, 29380, 17565, 17574, 41050, 41041, 41021, 17603,
        40994, 24573, 17628, 17648, 17763, 17651, 40931, 17673, 40878,
        17696, 40844, 40837, 40833, 40809, 40807, 40772, 17754, 24570,
        42269, 16851, 15293, 43783, 44214, 44180, 15675, 15699, 44102,
        15718, 15723, 44074, 15724, 44068, 44039, 15743, 44031, 44028,
        15749, 43969, 43967, 15793, 43924, 15822, 43899, 24734, 43875,
        43869, 43856, 29094, 43819, 15879, 43816, 15622, 15617, 44250,
        15459, 15304, 44722, 44699, 15334, 44686, 15345, 44672, 15424,
        44532, 15442, 44509, 44505, 15458, 44448, 44257, 44447, 44425,
        15504, 15511, 15522, 44390, 44357, 44355, 15559, 44322, 15567,
        44293, 44277, 43814, 15906, 16844, 15963, 43047, 43026, 16387,

In [11]:
# df          , sorted_ind              , title_name                       , top_n=10
# movies_df     genre_sim_sorted_ind      The Godfather <- 기준 영화         추출 영화 개수
def find_sim_movie(df, sorted_ind, title_name, top_n=10):

    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df["primaryTitle"] == title_name]
    print(title_movie)
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]

    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임.
    # dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)

    return df.iloc[similar_indexes]

In [12]:
similar_movies = find_sim_movie(title_basic, genre_sim_sorted_index, "Star Trek", 10)
similar_movies[["primaryTitle", "averageRating", "numVotes"]]

          tconst titleType primaryTitle originalTitle  isAdult  startYear endYear runtimeMinutes                   genres  averageRating  numVotes
29442  tt0796366     movie    Star Trek     Star Trek        0       2009      \N            127  Action,Adventure,Sci-Fi            7.9    565829
[[ 2721 40602 11114 38380 24970 26959 68981 33063 38232 38158]]

                              primaryTitle  averageRating  numVotes
2721                                Aliens            8.3    624087
40602                    Jupiter Ascending            5.3    172245
11114                    The Fifth Element            7.7    416584
38380                           Battleship            5.8    229748
24970                         Transformers            7.0    581372
26959   Captain America: The First Avenger            6.9    703172
68981                               Hornet            1.8       175
33063  Transformers: Revenge of the Fallen            6.0    373834
38232                        The Wolverine            6.7    414791
38158                            Predators            6.4    205458

In [13]:
C = title_basic["averageRating"].mean()
m = title_basic["numVotes"].quantile(0.6)  # 상위 0.6 값 추출
print("C:", round(C, 3), "m:", round(m, 3))

C: 5.89 m: 770.0

In [14]:
percentile = 0.6
m = title_basic["numVotes"].quantile(percentile)
C = title_basic["averageRating"].mean()


# record : movies_df
def weighted_vote_average(record):
    v = record["numVotes"]
    R = record["averageRating"]

    return ((v / (v + m)) * R) + ((m / (m + v)) * C)


title_basic["weighted_vote"] = title_basic.apply(weighted_vote_average, axis=1)

In [15]:
title_basic[["primaryTitle", "averageRating", "weighted_vote", "numVotes"]].sort_values(
    "weighted_vote", ascending=False
)[:10]

                                        primaryTitle  averageRating  weighted_vote  numVotes
8904                        The Shawshank Redemption            9.3       9.298807   2200571
49742                         CM101MMXI Fundamentals            9.2       9.141189     42563
64687                               Love in Kilnerry            9.9       9.077992      2986
60691                                       Aynabaji            9.2       9.071010     18987
46305                                         Wheels            9.2       9.063309     17874
27425                                The Dark Knight            9.0       8.998903   2182161
8832                                    Pulp Fiction            8.9       8.898660   1729296
13919  The Lord of the Rings: The Return of the King            8.9       8.898519   1564104
8052                                Schindler's List            8.9       8.897983   1148400
66826                                        Peranbu            9.1       8.892104     11118

In [17]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df["primaryTitle"] == title_name]
    title_index = title_movie.index.values

    # top_n의 2배에 해당하는 쟝르 유사성이 높은 index 추출
    similar_indexes = sorted_ind[title_index, : (top_n * 2)]
    similar_indexes = similar_indexes.reshape(-1)

    # 기준 영화 index는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]

    # top_n의 2배에 해당하는 후보군에서 weighted_vote 높은 순으로 top_n 만큼 추출
    # similar_indexes : 20개
    return df.iloc[similar_indexes].sort_values("weighted_vote", ascending=False)[
        :top_n
    ]


similar_movies = find_sim_movie(title_basic, genre_sim_sorted_index, "Interstellar", 5)
similar_movies[["primaryTitle", "averageRating", "weighted_vote", "genres"]]

                               primaryTitle  averageRating  weighted_vote                  genres
54496                           The Martian            8.0       7.997739  Adventure,Drama,Sci-Fi
28050                           I Am Legend            7.2       7.198466  Adventure,Drama,Sci-Fi
27467                  The Astronaut Farmer            6.3       6.285923  Adventure,Drama,Sci-Fi
4911   Es ist nicht leicht ein Gott zu sein            6.5       6.231582  Adventure,Drama,Sci-Fi
67012                 Antariksham 9000 kmph            6.1       6.006290  Adventure,Drama,Sci-Fi

---

In [ ]:
rating_scales = rating_scale[:5000000]

In [ ]:
ratings_matrix = rating_scales.pivot_table("rating", index="userId", columns="movieId")

In [ ]:
ratings_matrix.fillna(0, inplace=True)

In [ ]:
ratings_matrix.to_csv("./data/ratings_matrix.csv", index=False)

In [ ]:
ratings_matrix = pd.read_csv("./data/ratings_matrix.csv")
ratings_matrix.head()

In [ ]:
ratings_matrix.shape

In [45]:
movie

       movieId                                    title                                       genres
0            1                         Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
1            2                           Jumanji (1995)                   Adventure|Children|Fantasy
2            3                  Grumpier Old Men (1995)                               Comedy|Romance
3            4                 Waiting to Exhale (1995)                         Comedy|Drama|Romance
4            5       Father of the Bride Part II (1995)                                       Comedy
...        ...                                      ...                                          ...
58093   193876                  The Great Glinka (1946)                           (no genres listed)
58094   193878  Les tribulations d'une caissière (2011)                                       Comedy
58095   193880                 Her Name Was Mumu (2016)                                        Drama
58096   193882                             Flora (2017)                Adventure|Drama|Horror|Sci-Fi
58097   193886                              Leal (2018)                           Action|Crime|Drama

[58098 rows x 3 columns]

In [ ]:
rating = pd.read_csv("./data/ratings.csv")
del rating

In [48]:
rating.drop("timestamp", axis=1, inplace=True)

In [49]:
rating

          userId  movieId  rating
0              1      307     3.5
1              1      481     3.5
2              1     1091     1.5
3              1     1257     4.5
4              1     1449     4.5
...          ...      ...     ...
27753439  283228     8542     4.5
27753440  283228     8712     4.5
27753441  283228    34405     4.5
27753442  283228    44761     4.5
27753443  283228    54286     4.5

[27753444 rows x 3 columns]

In [50]:
rating_movies = pd.merge(rating, movie, on="movieId")

In [51]:
rating_movies

          userId  movieId  rating                                             title              genres
0              1      307     3.5  Three Colors: Blue (Trois couleurs: Bleu) (1993)               Drama
1              6      307     4.0  Three Colors: Blue (Trois couleurs: Bleu) (1993)               Drama
2             56      307     4.0  Three Colors: Blue (Trois couleurs: Bleu) (1993)               Drama
3             71      307     5.0  Three Colors: Blue (Trois couleurs: Bleu) (1993)               Drama
4             84      307     3.0  Three Colors: Blue (Trois couleurs: Bleu) (1993)               Drama
...          ...      ...     ...                                               ...                 ...
27753439  282403   167894     1.0                               Stranglehold (1994)              Action
27753440  282732   161572     3.5                          The Great Houdini (1976)               Drama
27753441  283000   117857     3.5                                    Hotline (2014)         Documentary
27753442  283000   133409     3.5                                    Barnum! (1986)  (no genres listed)
27753443  283000   142855     3.5                Paul Taylor Creative Domain (2014)         Documentary

[27753444 rows x 5 columns]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

item_sim = cosine_similarity(ratings_matrix, ratings_matrix)

item_sim_df = pd.DataFrame(
    data=item_sim, index=ratings_matrix.columns, columns=ratings_matrix.columns
)
print(item_sim_df.shape)
item_sim_df.head()